package main;
use JSON;

# ============================================================================
# CasambiUnit — FHEM device module for a single Casambi light
#
# Each device represents one Casambi unit (luminaire).  Devices are normally
# auto-created by CasambiGW when the ESP32 gateway connects.  They can also
# be defined manually:
#
#   define <name> CasambiUnit <gatewayName> <mac>
#
# The MAC address is the stable identifier; it is stored as the attribute
# "casambiMac" and survives Casambi unit-ID changes or network re-configs.
# The FUUID (used by homebridge/HomeKit) is generated by FHEM and never
# touched by this module, so HomeKit associations remain intact.
#
# Capabilities (CCT, vertical) are detected automatically from the gateway's
# hello message and stored as attributes.  setList, webCmd, genericDeviceType
# and homebridgeMapping are regenerated on each gateway (re-)connect.
#
# Commands accepted by SetFn:
#   on / off
#   brightness  0-100
#   colorTemp   Kelvin (>500) or Mired (<500, converted automatically)
#   vertical    0-255   (only on units with vertical capability)
# ============================================================================

sub CasambiUnit_Initialize {
    my $hash = shift;
    $hash->{DefFn}    = "CasambiUnit_Define";
    $hash->{UndefFn}  = "CasambiUnit_Undefine";
    $hash->{SetFn}    = "CasambiUnit_Set";
    $hash->{AttrList} = "casambiMac cctMin cctMax setList "
                      . $readingFnAttributes;
    return undef;
}

# ============================================================================
# Device lifecycle
# ============================================================================

# define Casambi_Lamp CasambiUnit <gwName> <mac>
sub CasambiUnit_Define {
    my ($hash, $def) = @_;
    my @args = split /\s+/, $def;
    return "Usage: define <name> CasambiUnit <gatewayName> <mac>" if @args < 4;

    my ($name, undef, $gwName, $mac) = @args;

    $hash->{GW_NAME}         = $gwName;
    $hash->{UPDATING_STATUS} = 0;

    # Persist MAC as attribute — set once; never overwrite a user-set value
    CommandAttr(undef, "$name casambiMac $mac")
        unless AttrVal($name, "casambiMac", "");

    readingsSingleUpdate($hash, "state", "initialized", 1);
    return undef;
}

sub CasambiUnit_Undefine {
    my ($hash, $name) = @_;
    RemoveInternalTimer($hash);
    return undef;
}

# ============================================================================
# SetFn — user / homebridge commands
# ============================================================================

sub CasambiUnit_Set {
    my ($hash, $name, $cmd, @args) = @_;

    # Suppress feedback loop while gateway is pushing state updates
    return undef if $hash->{UPDATING_STATUS};

    if ($cmd eq "?") {
        return "Unknown argument $cmd, choose one of "
             . AttrVal($name, "setList", "on:noArg off:noArg brightness:slider,0,1,100");
    }

    my $gwName = $hash->{GW_NAME};
    my $unitId = ReadingsVal($name, "casambiId", "");
    return "No casambiId assigned yet — waiting for gateway sync" unless $unitId;

    if ($cmd eq "on") {
        CasambiGW_SendCommand($gwName, $unitId, "on");
        readingsSingleUpdate($hash, "state", "on", 1);

    } elsif ($cmd eq "off") {
        CasambiGW_SendCommand($gwName, $unitId, "off");
        readingsSingleUpdate($hash, "state", "off", 1);

    } elsif ($cmd eq "brightness") {
        my $val = int($args[0] // 0);
        $val = 0   if $val < 0;
        $val = 100 if $val > 100;
        _CasambiUnit_Debounce($hash, "brightness",
            sub { CasambiGW_SendCommand($gwName, $unitId, "brightness", $val); });
        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "brightness", $val);
        readingsBulkUpdate($hash, "state",      $val > 0 ? "on" : "off");
        readingsEndUpdate($hash, 1);

    } elsif ($cmd eq "colorTemp") {
        my $val = int($args[0] // 0);
        # Accept both Kelvin (>500) and Mired (100-499, e.g. from homebridge)
        my $kelvin = ($val > 0 && $val < 500) ? int(1000000 / $val) : $val;
        my $cctMin = AttrVal($name, "cctMin", 2700);
        my $cctMax = AttrVal($name, "cctMax", 6500);
        $kelvin = $cctMin if $kelvin < $cctMin;
        $kelvin = $cctMax if $kelvin > $cctMax;
        _CasambiUnit_Debounce($hash, "colorTemp",
            sub { CasambiGW_SendCommand($gwName, $unitId, "colorTemp", $kelvin); });
        # Store Kelvin so the FHEM WebUI shows a human-readable value
        readingsSingleUpdate($hash, "colorTemp", $kelvin, 1);

    } elsif ($cmd eq "vertical") {
        my $val = int($args[0] // 0);
        $val = 0   if $val < 0;
        $val = 255 if $val > 255;
        _CasambiUnit_Debounce($hash, "vertical",
            sub { CasambiGW_SendCommand($gwName, $unitId, "vertical", $val); });
        readingsSingleUpdate($hash, "vertical", $val, 1);

    } else {
        return "Unknown set command '$cmd', choose one of "
             . AttrVal($name, "setList", "on:noArg off:noArg brightness:slider,0,1,100");
    }

    return undef;
}

# ============================================================================
# Debounce helper — delays analog commands by 300 ms to reduce BLE traffic
# ============================================================================

sub _CasambiUnit_Debounce {
    my ($hash, $type, $action) = @_;
    my $key = "debounce_" . $hash->{NAME} . "_$type";
    RemoveInternalTimer($key);
    InternalTimer(gettimeofday() + 0.3, $action, $key);
}

# ============================================================================
# UpdateFromState — apply a unit state object to FHEM readings.
# Called by CasambiGW for both "hello" snapshots and live "unit_state" pushes.
# ============================================================================

sub CasambiUnit_UpdateFromState {
    my ($hash, $unit) = @_;

    $hash->{UPDATING_STATUS} = 1;

    my $level  = $unit->{level} // 0;
    my $on     = defined($unit->{on}) ? $unit->{on} : ($level > 0);
    my $bright = int($level / 2.55 + 0.5);
    $bright = 100 if $bright > 100;

    readingsBeginUpdate($hash);
    readingsBulkUpdate($hash, "state",      $on ? "on" : "off");
    readingsBulkUpdate($hash, "brightness", $bright);
    readingsBulkUpdate($hash, "online",     $unit->{online} ? "true" : "false");
    readingsBulkUpdate($hash, "casambiId",  $unit->{id})   if defined $unit->{id};
    readingsBulkUpdate($hash, "casambiName",$unit->{name}) if defined $unit->{name};

    if (defined $unit->{vertical}) {
        readingsBulkUpdate($hash, "vertical", $unit->{vertical});
    }

    # colorTemp: raw 0-255 → Kelvin (for human-readable WebUI display)
    if (defined $unit->{colorTemp} && defined $unit->{cctMin} && defined $unit->{cctMax}) {
        my ($raw, $min, $max) = ($unit->{colorTemp}, $unit->{cctMin}, $unit->{cctMax});
        if ($max > $min) {
            my $kelvin = int($min + ($raw / 255.0) * ($max - $min) + 0.5);
            readingsBulkUpdate($hash, "colorTemp", $kelvin);
        }
    }

    readingsEndUpdate($hash, 1);
    $hash->{UPDATING_STATUS} = 0;
}

# ============================================================================
# SetCapabilities — called by CasambiGW on each hello.
# Updates capability-derived attributes: cctMin/Max, setList, webCmd,
# genericDeviceType, homebridgeMapping.
# ============================================================================

sub CasambiUnit_SetCapabilities {
    my ($hash, $unit) = @_;
    my $name = $hash->{NAME};

    my $hasCCT      = $unit->{hasCCT}     ? 1 : 0;
    my $hasVertical = $unit->{hasVertical} ? 1 : 0;
    my $cctMin      = $unit->{cctMin}  // 2700;
    my $cctMax      = $unit->{cctMax}  // 6500;

    # --- CCT range attributes ---
    if ($hasCCT) {
        _CasambiUnit_SetAttrIfChanged($name, "cctMin", $cctMin);
        _CasambiUnit_SetAttrIfChanged($name, "cctMax", $cctMax);
    }

    # --- setList (capability-dependent) ---
    my $setList = "on:noArg off:noArg brightness:slider,0,1,100";
    $setList .= " colorTemp:slider,$cctMin,1,$cctMax" if $hasCCT;
    $setList .= " vertical:slider,0,1,255"            if $hasVertical;
    _CasambiUnit_SetAttrIfChanged($name, "setList", $setList);

    # --- webCmd ---
    my $webCmd = "on:off:brightness";
    $webCmd .= ":colorTemp" if $hasCCT;
    $webCmd .= ":vertical"  if $hasVertical;
    _CasambiUnit_SetAttrIfChanged($name, "webCmd", $webCmd);

    # --- genericDeviceType ---
    _CasambiUnit_SetAttrIfChanged($name, "genericDeviceType", "light");

    # --- homebridgeMapping ---
    # Primary Lightbulb service: on/off + brightness
    my $hbMap = "on=state,valueOff=off,cmdOff=off,cmdOn=on"
              . " brightness=brightness,homekit=Brightness,cmd=brightness"
              .   ",minValue=0,maxValue=100";

    if ($hasCCT) {
        # FHEM stores Kelvin; HomeKit expects Mired.
        # expr converts the Kelvin reading → Mired for HomeKit display.
        # SetFn accepts Mired input from homebridge and converts back to Kelvin.
        my $minMired = int(1000000 / $cctMax);   # higher K → lower Mired
        my $maxMired = int(1000000 / $cctMin);
        $hbMap .= " colorTemperature=colorTemp,homekit=ColorTemperature"
               .  ",cmd=colorTemp,minValue=$minMired,maxValue=$maxMired"
               .  ",expr=int(1000000/\$val)";
    }

    if ($hasVertical) {
        # Second Lightbulb service for vertical light distribution control.
        # Named "<devicename>_vertical" so HomeKit shows it as a sibling accessory.
        my $vName = "${name}_vertical";
        $hbMap .= " on_v=state,valueOff=off,cmdOff=off,cmdOn=on"
               .  ",service_name=$vName"
               .  " brightness_v=vertical,homekit=Brightness,cmd=vertical"
               .  ",minValue=0,maxValue=255,service_name=$vName";
    }

    _CasambiUnit_SetAttrIfChanged($name, "homebridgeMapping", $hbMap);
}

# Set a FHEM attribute only when the value actually changed
# (avoids spurious attr-change events on every gateway reconnect)
sub _CasambiUnit_SetAttrIfChanged {
    my ($name, $attr, $newVal) = @_;
    return if AttrVal($name, $attr, "") eq $newVal;
    CommandAttr(undef, "$name $attr $newVal");
}

1;

=pod
=item device
=item summary FHEM device for a single Casambi light (child of CasambiGW)
=item summary_DE FHEM-Gerät für eine einzelne Casambi-Leuchte (Kind von CasambiGW)
=begin html

<a name="CasambiUnit"></a>
<h3>CasambiUnit</h3>
<ul>
  Represents a single Casambi luminaire.  Normally auto-created by
  <a href="#CasambiGW">CasambiGW</a>; can also be defined manually.
  The device is identified by its BLE MAC address (attribute
  <b>casambiMac</b>), so it survives Casambi unit-ID changes and
  HomeKit associations (FUUID) are preserved across restarts.
  <br><br>
  <b>Define</b><br>
  <code>define &lt;name&gt; CasambiUnit &lt;gatewayName&gt; &lt;mac&gt;</code>
  <br><br>
  <b>Set commands</b>
  <ul>
    <li><b>on / off</b></li>
    <li><b>brightness</b> 0-100</li>
    <li><b>colorTemp</b> &lt;Kelvin&gt; or &lt;Mired&gt; &mdash; values &lt;500
        are treated as Mired and converted automatically (CCT units only)</li>
    <li><b>vertical</b> 0-255 &mdash; vertical light distribution
        (units with vertical capability only)</li>
  </ul>
  <br>
  <b>Readings</b>
  <ul>
    <li><b>state</b> on|off|initialized</li>
    <li><b>brightness</b> 0-100 %</li>
    <li><b>colorTemp</b> Kelvin (CCT units only)</li>
    <li><b>vertical</b> 0-255 (vertical units only)</li>
    <li><b>online</b> true|false</li>
    <li><b>casambiId</b> current Casambi unit ID (may change after network re-config)</li>
    <li><b>casambiName</b> unit name as configured in the Casambi network</li>
  </ul>
  <br>
  <b>Managed attributes</b> (auto-set by CasambiGW, updated on each reconnect)
  <ul>
    <li><b>casambiMac</b> BLE MAC — stable hardware identifier, set once on creation</li>
    <li><b>cctMin / cctMax</b> CCT range in Kelvin from the Casambi network config</li>
    <li><b>setList</b> capability-dependent set command list</li>
    <li><b>webCmd</b> capability-dependent WebUI quick buttons</li>
    <li><b>genericDeviceType</b> always "light"</li>
    <li><b>homebridgeMapping</b> HomeKit mapping incl. K→Mired conversion for colorTemp
        and optional second Lightbulb service for vertical</li>
  </ul>
</ul>
=end html
=cut
