package main;

# ============================================================================
# CasambiUnit — FHEM device module for a single Casambi light
#
# Each device represents one Casambi unit (luminaire).  Devices are normally
# auto-created by CasambiGW when the ESP32 gateway connects.  They can also
# be defined manually:
#
#   define <name> CasambiUnit <gatewayName> <mac>
#
# The MAC address is the stable identifier; it is stored as the attribute
# "casambiMac" and survives Casambi unit-ID changes or network re-configs.
# The FUUID (used by homebridge/HomeKit) is generated by FHEM and never
# touched by this module, so HomeKit associations remain intact.
#
# Capabilities (CCT, vertical) are detected automatically from the gateway's
# hello message and stored as attributes.  setList, webCmd, genericDeviceType
# and homebridgeMapping are regenerated on each gateway (re-)connect.
#
# When a unit has vertical capability a companion CasambiVertical device
# (named <unitName>_vertical) is auto-created.  The companion receives its
# state from CasambiUnit_UpdateFromState and exposes a dedicated dimmer
# interface for homebridge.
#
# Commands accepted by SetFn:
#   on / off    ("on" restores the last non-zero brightness, like the
#                Casambi app — not a hard jump to 100%)
#   brightness  0-100
#   colorTemp   Kelvin (>500) or Mired (<500, converted automatically)
#   vertical    0-255   (only on units with vertical capability)
#
# Units whose fixture has two or more dimmer controls (e.g. Oligo Grace
# Uplight/Downlight) are driven per channel instead: one 0-100% set command
# per channel (named after the cloud control, e.g. dimmer0/dimmer1, or its
# channelNames alias), and on/off act on ALL channels atomically via the
# gateway's /state endpoint ("off" remembers the split, "on" restores it).
# ============================================================================

sub CasambiUnit_Initialize {
    my $hash = shift;
    $hash->{DefFn}    = "CasambiUnit_Define";
    $hash->{UndefFn}  = "CasambiUnit_Undefine";
    $hash->{SetFn}    = "CasambiUnit_Set";
    $hash->{AttrList} = "casambiMac cctMin cctMax setList channelNames "
                      . $readingFnAttributes;

    # CasambiVertical lives in the same file; FHEM only auto-calls the
    # Initialize function that matches the filename, so we register it here.
    # Setting LOADED=1 prevents FHEM from searching for a _CasambiVertical.pm
    # file when a device of this type is defined.
    CasambiVertical_Initialize($modules{CasambiVertical} //= {});
    $modules{CasambiVertical}{LOADED} = 1;

    return undef;
}

# ============================================================================
# Device lifecycle
# ============================================================================

# define Casambi_Lamp CasambiUnit <gwName> <mac>
sub CasambiUnit_Define {
    my ($hash, $def) = @_;
    my @args = split /\s+/, $def;
    return "Usage: define <name> CasambiUnit <gatewayName> <mac>" if @args < 4;

    my ($name, undef, $gwName, $mac) = @args;

    # Canonicalize the MAC (lowercase, colon-free) so it matches the normalized
    # keys CasambiGW uses for unit lookup. The Casambi cloud reports addresses
    # with or without colons; storing a consistent form keeps matching robust.
    $mac =~ s/://g;
    $mac = lc $mac;

    $hash->{GW_NAME}         = $gwName;
    $hash->{UPDATING_STATUS} = 0;

    # Persist MAC as attribute — set once; never overwrite a user-set value
    CommandAttr(undef, "$name casambiMac $mac")
        unless AttrVal($name, "casambiMac", "");

    readingsSingleUpdate($hash, "state", "initialized", 1);
    return undef;
}

sub CasambiUnit_Undefine {
    my ($hash, $name) = @_;
    RemoveInternalTimer($hash);
    return undef;
}

# ============================================================================
# SetFn — user / homebridge commands
# ============================================================================

sub CasambiUnit_Set {
    my ($hash, $name, $cmd, @args) = @_;

    # Suppress feedback loop while gateway is pushing state updates
    return undef if $hash->{UPDATING_STATUS};

    if ($cmd eq "?") {
        return "Unknown argument $cmd, choose one of "
             . AttrVal($name, "setList", "on:noArg off:noArg brightness:slider,0,1,100");
    }

    my $gwName = $hash->{GW_NAME};
    my $unitId = ReadingsVal($name, "casambiId", "");
    return "No casambiId assigned yet — waiting for gateway sync" unless $unitId;

    # --- Multi-dimmer units: per-channel commands + atomic on/off -----------
    # The channel list (control names) is filled by SetCapabilities from the
    # cloud controls; single-dimmer units have no "channels" reading and skip
    # this block entirely.
    my @chNames = split /,/, ReadingsVal($name, "channels", "");
    if (@chNames >= 2) {
        my ($alias, $revAlias) = _CasambiUnit_ChannelAliases($name);

        # Per-channel dimmer command — accepts the control name ("dimmer0")
        # or its channelNames alias ("up"), value in percent.
        my $ctrl = $revAlias->{lc $cmd} // lc $cmd;
        if (grep { $_ eq $ctrl } @chNames) {
            my $pct = int($args[0] // 0);
            $pct = 0   if $pct < 0;
            $pct = 100 if $pct > 100;
            my $raw = int($pct * 2.55 + 0.5);
            $raw = 255 if $raw > 255;
            _CasambiUnit_Debounce($hash, "ch_$ctrl", sub {
                CasambiGW_SendCommand($gwName, $unitId, "state", { $ctrl => $raw });
            });
            my $any = $pct > 0 ? 1 : 0;
            for my $c (@chNames) {
                next if $c eq $ctrl;
                $any = 1 if ReadingsVal($name, $alias->{$c} // $c, 0) > 0;
            }
            readingsBeginUpdate($hash);
            readingsBulkUpdate($hash, $alias->{$ctrl} // $ctrl, $pct);
            readingsBulkUpdate($hash, "state", $any ? "on" : "off");
            readingsEndUpdate($hash, 1);
            return undef;
        }

        if ($cmd eq "on" || $cmd eq "off") {
            # ALL dimmer channels in one atomic state write. "off" remembers
            # the current split; "on" keeps lit channels, restores the
            # remembered split when everything is off, and falls back to 100%
            # on every channel when no split is known (e.g. after a FHEM
            # restart — LAST_SPLIT is an internal and does not persist).
            my %pcts;
            if ($cmd eq "off") {
                my %split;
                for my $c (@chNames) {
                    my $p = ReadingsVal($name, $alias->{$c} // $c, 0);
                    $split{$c} = $p if $p > 0;
                }
                $hash->{LAST_SPLIT} = {%split} if %split;
                %pcts = map { $_ => 0 } @chNames;
            } else {
                my $anyLit = 0;
                for my $c (@chNames) {
                    my $p = ReadingsVal($name, $alias->{$c} // $c, 0);
                    $pcts{$c} = $p;
                    $anyLit = 1 if $p > 0;
                }
                if (!$anyLit) {
                    my $split = $hash->{LAST_SPLIT};
                    if (ref($split) eq 'HASH' && %$split) {
                        %pcts = map { $_ => $split->{$_} // 0 } @chNames;
                    } else {
                        %pcts = map { $_ => 100 } @chNames;
                    }
                }
            }
            my %send;
            for my $c (@chNames) {
                my $raw = int(($pcts{$c} // 0) * 2.55 + 0.5);
                $raw = 255 if $raw > 255;
                $send{$c} = $raw;
            }
            CasambiGW_SendCommand($gwName, $unitId, "state", \%send);
            my $any = grep { ($pcts{$_} // 0) > 0 } @chNames;
            readingsBeginUpdate($hash);
            readingsBulkUpdate($hash, $alias->{$_} // $_, $pcts{$_} // 0) for @chNames;
            readingsBulkUpdate($hash, "state", $any ? "on" : "off");
            readingsEndUpdate($hash, 1);
            return undef;
        }
        # Anything else (colorTemp, vertical, ...) is a single-control command
        # and falls through to the generic handling below.
    }

    if ($cmd eq "on") {
        # Restore the last non-zero brightness (tracked in LAST_BRIGHTNESS)
        # instead of forcing 100% — matches the Casambi app behaviour and
        # avoids the jump when HomeKit sends "On" after dimming. After a FHEM
        # restart the internal is empty; the brightness reading (statefile)
        # covers that window. Falls back to 100% when nothing is known.
        my $bright = $hash->{LAST_BRIGHTNESS}
                  // ReadingsVal($name, "brightness", 0);
        $bright = 100 if $bright <= 0 || $bright > 100;
        CasambiGW_SendCommand($gwName, $unitId, "brightness", $bright);
        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "brightness", $bright);
        readingsBulkUpdate($hash, "state",      "on");
        readingsEndUpdate($hash, 1);

    } elsif ($cmd eq "off") {
        CasambiGW_SendCommand($gwName, $unitId, "off");
        readingsSingleUpdate($hash, "state", "off", 1);

    } elsif ($cmd eq "brightness") {
        my $val = int($args[0] // 0);
        $val = 0   if $val < 0;
        $val = 100 if $val > 100;
        $hash->{LAST_BRIGHTNESS} = $val if $val > 0;
        _CasambiUnit_Debounce($hash, "brightness",
            sub { CasambiGW_SendCommand($gwName, $unitId, "brightness", $val); });
        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "brightness", $val);
        readingsBulkUpdate($hash, "state",      $val > 0 ? "on" : "off");
        readingsEndUpdate($hash, 1);

    } elsif ($cmd eq "colorTemp") {
        my $val = int($args[0] // 0);
        # Accept both Kelvin (>500) and Mired (100-499, e.g. from homebridge)
        my $kelvin = ($val > 0 && $val < 500) ? int(1000000 / $val) : $val;
        my $cctMin = AttrVal($name, "cctMin", 2700);
        my $cctMax = AttrVal($name, "cctMax", 6500);
        $kelvin = $cctMin if $kelvin < $cctMin;
        $kelvin = $cctMax if $kelvin > $cctMax;
        _CasambiUnit_Debounce($hash, "colorTemp",
            sub { CasambiGW_SendCommand($gwName, $unitId, "colorTemp", $kelvin); });
        # Store Kelvin so the FHEM WebUI shows a human-readable value
        readingsSingleUpdate($hash, "colorTemp", $kelvin, 1);

    } elsif ($cmd eq "vertical") {
        my $val = int($args[0] // 0);
        $val = 0   if $val < 0;
        $val = 255 if $val > 255;
        _CasambiUnit_Debounce($hash, "vertical",
            sub { CasambiGW_SendCommand($gwName, $unitId, "vertical", $val); });
        readingsSingleUpdate($hash, "vertical", $val, 1);

    } else {
        return "Unknown set command '$cmd', choose one of "
             . AttrVal($name, "setList", "on:noArg off:noArg brightness:slider,0,1,100");
    }

    return undef;
}

# ============================================================================
# Multi-dimmer channels — generic, cloud-derived
#
# A unit whose fixture has TWO OR MORE dimmer controls (e.g. Oligo Grace:
# independent Uplight/Downlight) is driven per channel instead of via the
# single brightness (which only reaches the first state byte). All channel
# writes go through the gateway's atomic /state endpoint, so several channels
# change in ONE BLE telegram and untouched controls keep their values.
# Everything here is derived from the cloud control list — no fixture-specific
# code; single-dimmer units keep the classic brightness handling unchanged.
# ============================================================================

# Return the unit's dimmer channels as [ { name, value }, ... ] — empty for
# units with fewer than two dimmer controls. Names come from the gateway
# ("name" per control, API >= 1.1); for older firmware they are derived the
# same way the ESP32 does it (cloud type + 0-based index on repetition).
sub _CasambiUnit_DimmerChannels {
    my ($unit) = @_;
    return [] unless ref($unit) eq 'HASH' && ref($unit->{controls}) eq 'ARRAY';
    my @dimmers = grep { ref($_) eq 'HASH' && ($_->{type} // '') eq 'dimmer' }
                  @{$unit->{controls}};
    return [] if @dimmers < 2;
    my @out;
    my $i = 0;
    for my $c (@dimmers) {
        push @out, { name  => lc($c->{name} // ("dimmer" . $i)),
                     value => $c->{value} // 0 };
        $i++;
    }
    return \@out;
}

# Parse the channelNames attribute ("<control>:<alias> ...", e.g.
# "dimmer0:up dimmer1:down"). Returns (fwd, rev): control name -> alias and
# lowercased alias -> control name. Pure display/command mapping — the wire
# always speaks the gateway's control names.
sub _CasambiUnit_ChannelAliases {
    my ($name) = @_;
    my (%fwd, %rev);
    for my $pair (split /\s+/, AttrVal($name, "channelNames", "")) {
        my ($ctrl, $alias) = split /:/, $pair, 2;
        next unless defined $alias && $alias ne ""
                 && $ctrl  =~ /^[a-z0-9_]+$/i
                 && $alias =~ /^[A-Za-z][A-Za-z0-9_\-]*$/;
        $fwd{lc $ctrl}  = $alias;
        $rev{lc $alias} = lc $ctrl;
    }
    return (\%fwd, \%rev);
}

# ============================================================================
# Debounce helper — delays analog commands by 300 ms to reduce BLE traffic
# ============================================================================

sub _CasambiUnit_Debounce {
    my ($hash, $type, $action) = @_;
    my $key = "debounce_" . $hash->{NAME} . "_$type";
    RemoveInternalTimer($key);
    InternalTimer(gettimeofday() + 0.3, $action, $key);
}

# ============================================================================
# UpdateFromState — apply a unit state object to FHEM readings.
# Called by CasambiGW for both "hello" snapshots and live "unit_state" pushes.
# ============================================================================

sub CasambiUnit_UpdateFromState {
    my ($hash, $unit) = @_;

    my $level  = $unit->{level} // 0;
    my $on     = defined($unit->{on}) ? $unit->{on} : ($level > 0);
    my $bright = int($level / 2.55 + 0.5);
    $bright = 100 if $bright > 100;

    # Multi-dimmer units: "on" means ANY channel lit — the gateway's on/level
    # fields only reflect the first state byte (first dimmer channel).
    my $channels = _CasambiUnit_DimmerChannels($unit);
    my ($chAlias) = _CasambiUnit_ChannelAliases($hash->{NAME});
    if (@$channels) {
        my $any = 0;
        for my $c (@$channels) { $any = 1 if ($c->{value} // 0) > 0; }
        $on = $any;
    }

    # Remember the last non-zero level for "set on" (restore instead of 100%).
    $hash->{LAST_BRIGHTNESS} = $bright if $bright > 0;

    {
        # `local` (block-scoped) instead of manual set/reset: the notify chain
        # triggered by readingsEndUpdate runs arbitrary user code — if that
        # dies, a manually set flag would stick at 1 and the device would
        # ignore every set command until the next FHEM restart.
        local $hash->{UPDATING_STATUS} = 1;

        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "state",      $on ? "on" : "off");
        # Multi-dimmer units get one percent reading per channel instead of the
        # single brightness (which would only mirror the first channel).
        readingsBulkUpdate($hash, "brightness", $bright) unless @$channels;
        readingsBulkUpdate($hash, "online",     $unit->{online} ? "true" : "false");
        readingsBulkUpdate($hash, "casambiId",  $unit->{id})   if defined $unit->{id};
        readingsBulkUpdate($hash, "casambiName",$unit->{name}) if defined $unit->{name};

        for my $c (@$channels) {
            my $pct = int(($c->{value} // 0) / 2.55 + 0.5);
            $pct = 100 if $pct > 100;
            readingsBulkUpdate($hash, $chAlias->{$c->{name}} // $c->{name}, $pct);
        }

        if (ref($unit->{controls}) eq 'ARRAY') {
            # Generic, cloud-derived channel readings: one reading per fixture
            # control, named by the control type reported by the cloud
            # (dimmer/vertical/temperature/white/slider/...). New control types
            # therefore surface as readings automatically, without code changes.
            # temperature is reported in Kelvin (resolved by the gateway from the
            # raw value + bounds); "colorTemp" is kept as an alias so the existing
            # homebridgeMapping / dashboards keep working.
            for my $c (@{$unit->{controls}}) {
                next unless ref($c) eq 'HASH' && defined $c->{type};
                my $t = $c->{type};
                next if $t eq 'dimmer' || $t eq 'onoff';   # covered by brightness/state
                if ($t eq 'temperature') {
                    my $k = $c->{kelvin};
                    next unless defined $k;
                    readingsBulkUpdate($hash, "temperature", $k);
                    readingsBulkUpdate($hash, "colorTemp",   $k);   # compat alias
                } elsif (defined $c->{value}) {
                    readingsBulkUpdate($hash, $t, $c->{value});
                }
            }
        } else {
            # Fallback for gateways/configs without the generic controls array.
            if (defined $unit->{vertical}) {
                readingsBulkUpdate($hash, "vertical", $unit->{vertical});
            }
            if (defined $unit->{colorTemp} && defined $unit->{cctMin} && defined $unit->{cctMax}) {
                my ($raw, $min, $max) = ($unit->{colorTemp}, $unit->{cctMin}, $unit->{cctMax});
                if ($max > $min) {
                    my $kelvin = int($min + ($raw / 255.0) * ($max - $min) + 0.5);
                    readingsBulkUpdate($hash, "colorTemp", $kelvin);
                }
            }
        }

        readingsEndUpdate($hash, 1);
    }

    # Forward vertical state to companion CasambiVertical device. Prefer the
    # generic control value; fall back to the legacy field.
    my $vval;
    if (ref($unit->{controls}) eq 'ARRAY') {
        for my $c (@{$unit->{controls}}) {
            $vval = $c->{value}
                if ref($c) eq 'HASH' && ($c->{type} // '') eq 'vertical';
        }
    }
    $vval = $unit->{vertical} unless defined $vval;
    if (defined $vval) {
        my $vName = $hash->{NAME} . "_vertical";
        if ($defs{$vName} && ($defs{$vName}->{TYPE} // "") eq "CasambiVertical") {
            CasambiVertical_UpdateFromParent($defs{$vName}, $vval, $on);
        }
    }
}

# ============================================================================
# SetCapabilities — called by CasambiGW on each hello.
# Updates capability-derived attributes: cctMin/Max, setList, webCmd,
# genericDeviceType, homebridgeMapping.
# Auto-creates a CasambiVertical companion device when hasVertical is set.
# ============================================================================

sub CasambiUnit_SetCapabilities {
    my ($hash, $unit) = @_;
    my $name = $hash->{NAME};

    my $hasCCT      = $unit->{hasCCT}     ? 1 : 0;
    my $hasVertical = $unit->{hasVertical} ? 1 : 0;
    my $cctMin      = $unit->{cctMin}  // 2700;
    my $cctMax      = $unit->{cctMax}  // 6500;

    # Prefer the authoritative cloud controls when present: capabilities and the
    # Kelvin range are derived from the fixture control list rather than the
    # heuristic flags.
    if (ref($unit->{controls}) eq 'ARRAY') {
        ($hasCCT, $hasVertical) = (0, 0);
        for my $c (@{$unit->{controls}}) {
            next unless ref($c) eq 'HASH';
            my $t = $c->{type} // '';
            $hasVertical = 1 if $t eq 'vertical';
            if ($t eq 'temperature') {
                $hasCCT = 1;
                $cctMin = $c->{min} if defined $c->{min};
                $cctMax = $c->{max} if defined $c->{max};
            }
        }
    }

    # --- CCT range attributes ---
    if ($hasCCT) {
        _CasambiUnit_SetAttrIfChanged($name, "cctMin", $cctMin);
        _CasambiUnit_SetAttrIfChanged($name, "cctMax", $cctMax);
    }

    # --- Multi-dimmer channel list (generic, from the cloud controls) ---
    # Persisted as a reading so SetFn knows the channels right after a FHEM
    # restart (before the first hello). Display names honour channelNames.
    my $channels = _CasambiUnit_DimmerChannels($unit);
    my @disp;
    if (@$channels) {
        my ($chAlias) = _CasambiUnit_ChannelAliases($name);
        @disp = map { $chAlias->{$_->{name}} // $_->{name} } @$channels;
        my $chList = join(",", map { $_->{name} } @$channels);
        readingsSingleUpdate($hash, "channels", $chList, 1)
            if ReadingsVal($name, "channels", "") ne $chList;
    }

    # --- setList (capability-dependent) ---
    # Multi-dimmer units: one percent slider per channel instead of the single
    # brightness (which would only drive the first channel via SetLevel).
    my $setList = @$channels
        ? "on:noArg off:noArg " . join(" ", map { "$_:slider,0,1,100" } @disp)
        : "on:noArg off:noArg brightness:slider,0,1,100";
    $setList .= " colorTemp:slider,$cctMin,1,$cctMax" if $hasCCT;
    $setList .= " vertical:slider,0,1,255"            if $hasVertical;
    _CasambiUnit_SetAttrIfChanged($name, "setList", $setList);

    # --- webCmd ---
    my $webCmd = @$channels
        ? "on:off:" . join(":", @disp)
        : "on:off:brightness";
    $webCmd .= ":colorTemp" if $hasCCT;
    $webCmd .= ":vertical"  if $hasVertical && !@$channels;
    _CasambiUnit_SetAttrIfChanged($name, "webCmd", $webCmd);

    # --- genericDeviceType ---
    _CasambiUnit_SetAttrIfChanged($name, "genericDeviceType", "light");

    # --- homebridgeMapping (homebridge-platform-fhem classic format) ---
    # cmdOn/cmdOff tell homebridge which set-command to use for the On
    # characteristic; valueOff is the FHEM reading value that means "off".
    # Brightness uses homekit= to name the HomeKit characteristic and cmd=
    # for the FHEM set command.
    my $hbMap = "On=state,valueOff=off,cmdOff=off,cmdOn=on";

    # Multi-dimmer units map only On/Off by default: HomeKit's single
    # Brightness characteristic cannot represent independent channels. Map
    # individual channels manually via the homebridgeMapping attribute if
    # desired (the per-channel percent readings/commands are ready for it).
    $hbMap .= " Brightness=brightness,homekit=Brightness,cmd=brightness"
           .    ",minValue=0,maxValue=100"
        unless @$channels;

    if ($hasCCT) {
        # FHEM stores Kelvin; HomeKit expects Mired.
        # expr converts Kelvin → Mired for HomeKit display.
        # SetFn accepts Mired (<500) from homebridge and clamps to cctMin/Max.
        # Use the full HomeKit standard range (140-500 Mired = ~7100-2000K) so
        # HomeKit renders the full colour-temperature picker; out-of-range values
        # are clamped to the device limits inside SetFn.
        $hbMap .= " ColorTemperature=colorTemp,homekit=ColorTemperature"
               .  ",cmd=colorTemp,minValue=140,maxValue=500"
               .  ",expr=int(1000000/\$val)";
    }

    _CasambiUnit_SetAttrIfChanged($name, "homebridgeMapping", $hbMap);

    # --- Companion CasambiVertical device ---
    if ($hasVertical) {
        my $vName = "${name}_vertical";
        unless ($defs{$vName}) {
            Log3 $name, 3, "$name: Auto-creating CasambiVertical '$vName'";
            fhem("define $vName CasambiVertical $name");
        }
        # Keep capability attributes in sync on every reconnect
        # (handles devices created before an attribute was added)
        _CasambiUnit_SetAttrIfChanged($vName, "genericDeviceType", "light");
        _CasambiUnit_SetAttrIfChanged($vName, "setList",
            "on:noArg off:noArg pct:slider,0,1,100");
        _CasambiUnit_SetAttrIfChanged($vName, "homebridgeMapping",
            "On=state,valueOff=off,cmdOff=off,cmdOn=on"
          . " Brightness=pct,homekit=Brightness,cmd=pct,minValue=0,maxValue=100");
    }
}

# Set a FHEM attribute only when the value actually changed
# (avoids spurious attr-change events on every gateway reconnect)
sub _CasambiUnit_SetAttrIfChanged {
    my ($name, $attr, $newVal) = @_;
    return if AttrVal($name, $attr, "") eq $newVal;
    CommandAttr(undef, "$name $attr $newVal");
}

1;

# ============================================================================
# ============================================================================
# CasambiVertical — companion dimmer device for vertical light distribution
#
# Auto-created by CasambiUnit_SetCapabilities when a unit has vertical
# capability.  It maps the 0-255 vertical value to a 0-100% dimmer pct
# reading so that homebridge-platform-fhem can expose it as a second
# Lightbulb accessory.
#
# Direction convention (matches Casambi):
#   pct  0% → vertical   0  (light fully directed upward)
#   pct 100% → vertical 255  (light fully directed downward)
#
# The device is named <parentUnit>_vertical.
# It does NOT have its own webCmd — it is driven from the parent unit's
# FHEM WebUI via the "vertical" slider or via homebridge.
#
# Define:
#   define <name> CasambiVertical <parentUnitName>
# ============================================================================

package main;

sub CasambiVertical_Initialize {
    my $hash = shift;
    $hash->{DefFn}    = "CasambiVertical_Define";
    $hash->{UndefFn}  = "CasambiVertical_Undefine";
    $hash->{SetFn}    = "CasambiVertical_Set";
    $hash->{AttrList} = "setList " . $readingFnAttributes;
    return undef;
}

sub CasambiVertical_Define {
    my ($hash, $def) = @_;
    my @args = split /\s+/, $def;
    return "Usage: define <name> CasambiVertical <parentUnitName>" if @args < 3;

    my ($name, undef, $parentName) = @args;
    $hash->{PARENT_NAME}     = $parentName;
    $hash->{UPDATING_STATUS} = 0;

    _CasambiVertical_SetAttrIfChanged($name, "genericDeviceType", "light");
    _CasambiVertical_SetAttrIfChanged($name, "setList",
        "on:noArg off:noArg pct:slider,0,1,100");
    _CasambiVertical_SetAttrIfChanged($name, "homebridgeMapping",
        "On=state,valueOff=off,cmdOff=off,cmdOn=on"
      . " Brightness=pct,homekit=Brightness,cmd=pct,minValue=0,maxValue=100");

    readingsSingleUpdate($hash, "state", "initialized", 1);
    return undef;
}

sub CasambiVertical_Undefine {
    my ($hash, $name) = @_;
    RemoveInternalTimer($hash);
    return undef;
}

# ============================================================================
# SetFn — pct command (0-100%) maps to vertical 0-255 on the parent unit
# ============================================================================

sub CasambiVertical_Set {
    my ($hash, $name, $cmd, @args) = @_;

    return undef if $hash->{UPDATING_STATUS};

    if ($cmd eq "?") {
        return "Unknown argument $cmd, choose one of on:noArg off:noArg pct:slider,0,1,100";
    }

    my $parentName = $hash->{PARENT_NAME};
    my $parentHash = $defs{$parentName};
    return "Parent unit '$parentName' not found" unless $parentHash;

    my $gwName = $parentHash->{GW_NAME} // return "Parent unit has no GW_NAME";
    my $unitId = ReadingsVal($parentName, "casambiId", "");
    return "No casambiId on parent unit yet" unless $unitId;

    if ($cmd eq "on") {
        # Restore last pct or default to 50%
        my $lastPct = ReadingsVal($name, "pct", 50);
        $lastPct = 50 if $lastPct == 0;
        my $vertical = int($lastPct * 2.55 + 0.5);
        $vertical = 255 if $vertical > 255;
        CasambiGW_SendCommand($gwName, $unitId, "vertical", $vertical);
        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "pct",   $lastPct);
        readingsBulkUpdate($hash, "state", "on");
        readingsEndUpdate($hash, 1);

    } elsif ($cmd eq "off") {
        CasambiGW_SendCommand($gwName, $unitId, "vertical", 0);
        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "pct",   0);
        readingsBulkUpdate($hash, "state", "off");
        readingsEndUpdate($hash, 1);

    } elsif ($cmd eq "pct") {
        my $pct = int($args[0] // 0);
        $pct = 0   if $pct < 0;
        $pct = 100 if $pct > 100;
        my $vertical = int($pct * 2.55 + 0.5);
        $vertical = 255 if $vertical > 255;
        _CasambiVertical_Debounce($hash, sub {
            CasambiGW_SendCommand($gwName, $unitId, "vertical", $vertical);
        });
        readingsBeginUpdate($hash);
        readingsBulkUpdate($hash, "pct",   $pct);
        readingsBulkUpdate($hash, "state", $pct > 0 ? "on" : "off");
        readingsEndUpdate($hash, 1);

    } else {
        return "Unknown command '$cmd', choose one of on:noArg off:noArg pct:slider,0,1,100";
    }

    return undef;
}

# ============================================================================
# UpdateFromParent — called by CasambiUnit_UpdateFromState
# vertical: raw 0-255 from ESP32;  pct: 0-100 for homebridge
# ============================================================================

sub CasambiVertical_UpdateFromParent {
    my ($hash, $vertical, $parentOn) = @_;

    # local: restored even when a notify handler in the event chain dies —
    # a stuck flag would permanently suppress set commands (see CasambiUnit).
    local $hash->{UPDATING_STATUS} = 1;

    my $pct = int($vertical / 2.55 + 0.5);
    $pct = 100 if $pct > 100;

    readingsBeginUpdate($hash);
    readingsBulkUpdate($hash, "pct",      $pct);
    readingsBulkUpdate($hash, "vertical", $vertical);
    readingsBulkUpdate($hash, "state",    $pct > 0 ? "on" : "off");
    readingsEndUpdate($hash, 1);
}

sub _CasambiVertical_Debounce {
    my ($hash, $action) = @_;
    my $key = "debounce_" . $hash->{NAME} . "_vertical";
    RemoveInternalTimer($key);
    InternalTimer(gettimeofday() + 0.3, $action, $key);
}

sub _CasambiVertical_SetAttrIfChanged {
    my ($name, $attr, $newVal) = @_;
    return if AttrVal($name, $attr, "") eq $newVal;
    CommandAttr(undef, "$name $attr $newVal");
}

1;

=pod
=item device
=item summary FHEM device for a single Casambi light (child of CasambiGW)
=item summary_DE FHEM-Gerät für eine einzelne Casambi-Leuchte (Kind von CasambiGW)
=begin html

<a name="CasambiUnit"></a>
<h3>CasambiUnit</h3>
<ul>
  Represents a single Casambi luminaire.  Normally auto-created by
  <a href="#CasambiGW">CasambiGW</a>; can also be defined manually.
  The device is identified by its BLE MAC address (attribute
  <b>casambiMac</b>), so it survives Casambi unit-ID changes and
  HomeKit associations (FUUID) are preserved across restarts.
  <br><br>
  <b>Define</b><br>
  <code>define &lt;name&gt; CasambiUnit &lt;gatewayName&gt; &lt;mac&gt;</code>
  <br><br>
  <b>Set commands</b>
  <ul>
    <li><b>on</b> &mdash; restores the last non-zero brightness (like the
        Casambi app); falls back to 100% when no previous level is known</li>
    <li><b>off</b></li>
    <li><b>brightness</b> 0-100</li>
    <li><b>colorTemp</b> &lt;Kelvin&gt; or &lt;Mired&gt; &mdash; values &lt;500
        are treated as Mired and converted automatically (CCT units only)</li>
    <li><b>vertical</b> 0-255 &mdash; vertical light distribution
        (units with vertical capability only)</li>
    <li><b>&lt;channel&gt;</b> 0-100 &mdash; per-channel dimmer command on
        units whose fixture has two or more dimmer controls (e.g. Oligo Grace
        Uplight/Downlight). Channel commands are named after the cloud control
        (<code>dimmer0</code>, <code>dimmer1</code>, &hellip;) or the alias set
        via the <b>channelNames</b> attribute. All channel writes are applied
        atomically by the gateway (<code>POST /api/units/:id/state</code>);
        <b>on</b>/<b>off</b> then act on all channels together: <em>off</em>
        remembers the current split, <em>on</em> restores it (falling back to
        100% on every channel when no split is known). On these units the
        single <em>brightness</em> command/reading is replaced by the
        per-channel readings.</li>
  </ul>
  <br>
  <b>Readings</b>
  <ul>
    <li><b>state</b> on|off|initialized</li>
    <li><b>brightness</b> 0-100 %</li>
    <li>one reading per channel, <b>named by the cloud control type</b> (derived
        from the gateway's <code>controls</code> data): e.g.
        <b>vertical</b> 0-255, <b>temperature</b> Kelvin, and future types
        (white, slider, &hellip;) appear automatically</li>
    <li><b>temperature</b> Kelvin (units with a temperature control)</li>
    <li><b>colorTemp</b> compatibility alias of temperature (Kelvin), kept for
        existing dashboards and the HomeKit mapping</li>
    <li><b>vertical</b> 0-255 (units with a vertical control)</li>
    <li><b>online</b> true|false</li>
    <li><b>casambiId</b> current Casambi unit ID (may change after network re-config)</li>
    <li><b>casambiName</b> unit name as configured in the Casambi network</li>
    <li><b>channels</b> comma-separated control names of a multi-dimmer unit
        (e.g. <code>dimmer0,dimmer1</code>); absent on single-dimmer units</li>
    <li><b>&lt;channel&gt;</b> 0-100 % &mdash; one reading per dimmer channel
        of a multi-dimmer unit, named after the control or its
        <b>channelNames</b> alias</li>
  </ul>
  <br>
  <b>User attributes</b>
  <ul>
    <li><b>channelNames</b> &mdash; display aliases for the dimmer channels of
        a multi-dimmer unit, e.g.
        <code>attr &lt;unit&gt; channelNames dimmer0:up dimmer1:down</code>.
        Renames the readings, set commands and WebUI sliders; the gateway
        communication always uses the original control names. Set the
        attribute before the next gateway reconnect (or trigger one) so
        setList/webCmd are regenerated with the aliases.</li>
  </ul>
  <br>
  <b>Managed attributes</b> (auto-set by CasambiGW, updated on each reconnect)
  <ul>
    <li><b>casambiMac</b> BLE MAC &mdash; stable hardware identifier, set once on creation</li>
    <li><b>cctMin / cctMax</b> CCT range in Kelvin from the Casambi network config</li>
    <li><b>setList</b> capability-dependent set command list</li>
    <li><b>webCmd</b> capability-dependent WebUI quick buttons</li>
    <li><b>genericDeviceType</b> always "light"</li>
    <li><b>homebridgeMapping</b> HomeKit mapping incl. K&rarr;Mired conversion for colorTemp</li>
  </ul>
  <br>
  Units with vertical capability automatically get a companion
  <a href="#CasambiVertical">CasambiVertical</a> device (named
  <em>&lt;unitName&gt;_vertical</em>).
</ul>

<a name="CasambiVertical"></a>
<h3>CasambiVertical</h3>
<ul>
  Companion dimmer device for the vertical light-distribution channel of a
  <a href="#CasambiUnit">CasambiUnit</a>.  Auto-created by the parent unit;
  should not be defined manually.
  <br><br>
  The vertical raw value (0-255) is mapped to a percentage (0-100%) so that
  homebridge-platform-fhem can expose it as a Lightbulb Brightness control.
  <ul>
    <li>pct &nbsp;0% &rarr; vertical &nbsp;&nbsp;0 (light fully upward)</li>
    <li>pct 100% &rarr; vertical 255 (light fully downward)</li>
  </ul>
  <br>
  <b>Define</b><br>
  <code>define &lt;name&gt; CasambiVertical &lt;parentUnitName&gt;</code>
  <br><br>
  <b>Set commands</b>
  <ul>
    <li><b>on</b> &mdash; restores last non-zero pct (defaults to 50%)</li>
    <li><b>off</b> &mdash; sets pct to 0 (vertical = 0, light fully upward)</li>
    <li><b>pct</b> 0-100</li>
  </ul>
  <br>
  <b>Readings</b>
  <ul>
    <li><b>state</b> on|off|initialized</li>
    <li><b>pct</b> 0-100 (percentage, used by homebridge)</li>
    <li><b>vertical</b> 0-255 (raw Casambi value)</li>
  </ul>
  <br>
  <b>Managed attributes</b>
  <ul>
    <li><b>genericDeviceType</b> always "light"</li>
    <li><b>homebridgeMapping</b>
        <code>On=state,valueOff=off,cmdOff=off,cmdOn=on
        Brightness=pct,homekit=Brightness,cmd=pct,minValue=0,maxValue=100</code></li>
  </ul>
</ul>

=end html
=cut
