"""
PlatformIO pre-build script — inject FIRMWARE_BUILD from git commit count.

The build number is the total number of commits reachable from the tip of the
main branch (git rev-list --count origin/main).  This value:
  - is 0 on a fresh clone before any fetching (graceful fallback)
  - strictly increases with every merge / commit to main
  - is the same regardless of which feature branch you build from, because it
    counts only main-branch commits

The number is written to src/firmware_build.h (gitignored), which config.h
includes via __has_include with a fallback of 0.  It is NOT injected as a
compiler flag on purpose: SCons does not recompile an unchanged source file
just because an injected -D flag changed, so a flag-based number silently
survives incremental builds and the device keeps reporting a stale build
(observed in practice).  A generated header changes the *file content*, which
the dependency scanner does track — exactly the translation units that use
FIRMWARE_BUILD recompile, and only when the number actually changed (the file
is rewritten only on a value change, so unchanged rebuilds stay no-ops).
"""

import os
import subprocess
Import("env")

HEADER_TEMPLATE = """\
// Auto-generated by scripts/build_number.py — do not edit, not tracked in
// git.  See the FIRMWARE_BUILD section in src/config.h for how this file is
// consumed and why the number is delivered as a header instead of a -D flag.
#define FIRMWARE_BUILD {build_num}
"""


def get_build_number():
    # Try origin/main first (reflects the published state), fall back to main,
    # then HEAD, then 0 (e.g. shallow clone or no git at all).
    for ref in ("origin/main", "main", "HEAD"):
        try:
            out = subprocess.check_output(
                ["git", "rev-list", "--count", ref],
                stderr=subprocess.DEVNULL,
                cwd=env.subst("$PROJECT_DIR"),
            )
            return int(out.strip().decode())
        except Exception:
            continue
    return 0


def write_header(path, build_num):
    content = HEADER_TEMPLATE.format(build_num=build_num)
    try:
        with open(path, "r") as f:
            if f.read() == content:
                return  # unchanged — keep the old mtime, no recompile
    except OSError:
        pass
    if build_num == 0 and os.path.exists(path):
        # git unavailable but a previously generated number exists: a stale
        # real number beats overwriting it with 0.
        print("*** FIRMWARE_BUILD: git unavailable, keeping existing header ***")
        return
    with open(path, "w") as f:
        f.write(content)


build_num = get_build_number()
print(f"*** FIRMWARE_BUILD = {build_num} (git commit count on main) ***")
write_header(os.path.join(env.subst("$PROJECT_DIR"), "src", "firmware_build.h"),
             build_num)
